import { 
  FileText, 
  Book, 
  Layers, 
  Zap, 
  Code, 
  Shield, 
  Settings, 
  Plus, 
  Folder, 
  Link as LinkIcon, 
  Image as ImageIcon, 
  List as ListIcon, 
  Terminal, 
  Database, 
  Cloud, 
  Cpu, 
  Package, 
  GitBranch, 
  Wrench, 
  Grid, 
  Compass, 
  Hash, 
  Map as MapIcon, 
  BarChart, 
  PieChart, 
  Activity, 
  Globe, 
  Mail, 
  Bell, 
  Share, 
  Lock, 
  Key, 
  Eye, 
  Users, 
  Calendar, 
  Monitor, 
  Download, 
  Info, 
  HelpCircle, 
  CheckCircle,
  AlertCircle,
  Archive,
  ArrowRight,
  AtSign,
  Award,
  Bookmark,
  Briefcase,
  Camera,
  Clipboard,
  Clock,
  Coffee,
  CreditCard,
  Edit,
  ExternalLink,
  File,
  Filter,
  Flag,
  Gift,
  Heart,
  Home,
  Inbox,
  Layout,
  LifeBuoy,
  LogOut,
  Maximize,
  Menu,
  MessageSquare,
  Mic,
  Moon,
  Music,
  Paperclip,
  Phone,
  Play,
  Printer,
  Radio,
  RefreshCw,
  Search,
  Send,
  Server,
  ShoppingCart,
  Smartphone,
  Speaker,
  Star,
  Sun,
  Tag,
  Target,
  ThumbsUp,
  Trash,
  Truck,
  Tv,
  Twitter,
  User,
  Video,
  Volume2,
  Wifi
} from 'lucide-react';

export const icons = [
  { name: 'FileText', icon: FileText },
  { name: 'Book', icon: Book },
  { name: 'Layers', icon: Layers },
  { name: 'Zap', icon: Zap },
  { name: 'Code', icon: Code },
  { name: 'Shield', icon: Shield },
  { name: 'Settings', icon: Settings },
  { name: 'Plus', icon: Plus },
  { name: 'Folder', icon: Folder },
  { name: 'Link', icon: LinkIcon },
  { name: 'Image', icon: ImageIcon },
  { name: 'List', icon: ListIcon },
  { name: 'Terminal', icon: Terminal },
  { name: 'Database', icon: Database },
  { name: 'Cloud', icon: Cloud },
  { name: 'Cpu', icon: Cpu },
  { name: 'Package', icon: Package },
  { name: 'GitBranch', icon: GitBranch },
  { name: 'Wrench', icon: Wrench },
  { name: 'Grid', icon: Grid },
  { name: 'Compass', icon: Compass },
  { name: 'Hash', icon: Hash },
  { name: 'Map', icon: MapIcon },
  { name: 'BarChart', icon: BarChart },
  { name: 'PieChart', icon: PieChart },
  { name: 'Activity', icon: Activity },
  { name: 'Globe', icon: Globe },
  { name: 'Mail', icon: Mail },
  { name: 'Bell', icon: Bell },
  { name: 'Share', icon: Share },
  { name: 'Lock', icon: Lock },
  { name: 'Key', icon: Key },
  { name: 'Eye', icon: Eye },
  { name: 'Users', icon: Users },
  { name: 'Calendar', icon: Calendar },
  { name: 'Monitor', icon: Monitor },
  { name: 'Download', icon: Download },
  { name: 'Info', icon: Info },
  { name: 'HelpCircle', icon: HelpCircle },
  { name: 'CheckCircle', icon: CheckCircle },
  { name: 'AlertCircle', icon: AlertCircle },
  { name: 'Archive', icon: Archive },
  { name: 'ArrowRight', icon: ArrowRight },
  { name: 'AtSign', icon: AtSign },
  { name: 'Award', icon: Award },
  { name: 'Bookmark', icon: Bookmark },
  { name: 'Briefcase', icon: Briefcase },
  { name: 'Camera', icon: Camera },
  { name: 'Clipboard', icon: Clipboard },
  { name: 'Clock', icon: Clock },
  { name: 'Coffee', icon: Coffee },
  { name: 'CreditCard', icon: CreditCard },
  { name: 'Edit', icon: Edit },
  { name: 'ExternalLink', icon: ExternalLink },
  { name: 'File', icon: File },
  { name: 'Filter', icon: Filter },
  { name: 'Flag', icon: Flag },
  { name: 'Gift', icon: Gift },
  { name: 'Heart', icon: Heart },
  { name: 'Home', icon: Home },
  { name: 'Inbox', icon: Inbox },
  { name: 'Layout', icon: Layout },
  { name: 'LifeBuoy', icon: LifeBuoy },
  { name: 'LogOut', icon: LogOut },
  { name: 'Maximize', icon: Maximize },
  { name: 'Menu', icon: Menu },
  { name: 'MessageSquare', icon: MessageSquare },
  { name: 'Mic', icon: Mic },
  { name: 'Moon', icon: Moon },
  { name: 'Music', icon: Music },
  { name: 'Paperclip', icon: Paperclip },
  { name: 'Phone', icon: Phone },
  { name: 'Play', icon: Play },
  { name: 'Printer', icon: Printer },
  { name: 'Radio', icon: Radio },
  { name: 'RefreshCw', icon: RefreshCw },
  { name: 'Search', icon: Search },
  { name: 'Send', icon: Send },
  { name: 'Server', icon: Server },
  { name: 'ShoppingCart', icon: ShoppingCart },
  { name: 'Smartphone', icon: Smartphone },
  { name: 'Speaker', icon: Speaker },
  { name: 'Star', icon: Star },
  { name: 'Sun', icon: Sun },
  { name: 'Tag', icon: Tag },
  { name: 'Target', icon: Target },
  { name: 'ThumbsUp', icon: ThumbsUp },
  { name: 'Trash', icon: Trash },
  { name: 'Truck', icon: Truck },
  { name: 'Tv', icon: Tv },
  { name: 'Twitter', icon: Twitter },
  { name: 'User', icon: User },
  { name: 'Video', icon: Video },
  { name: 'Volume2', icon: Volume2 },
  { name: 'Wifi', icon: Wifi }
];
